name: bloc_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter_bloc: ^8.0.1
  bloc: ^8.0.2
  equatable: ^2.0.3
  http: ^0.13.4
  flutter_rating_bar: ^4.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
fonts:
- family: Montserrat
  fonts:
    - asset: assets/fonts/Montserrat-Black.ttf
    - asset: assets/fonts/Montserrat-Light.ttf
    - asset: assets/fonts/Montserrat-Regular.ttf
      style: italic
  

  uses-material-design: true
